apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  platform: tanzu-ipp

# Inherit everything from this base
bases:
  - ../base

# Add additional resources for this environment
resources:
  - resources/htdocs-configmap.yaml

# Patches can be defined as YAML merge
patches:
  - patches/htdocs-configmap.yaml # Overrides index.html and add page3.txt

# Or patches defined in JSON/RFC-6902 style
patchesJson6902:
  - path: patches/htdocs-page2.json # Removes the page2.txt item
    target:
      name: htdocs-static
      kind: ConfigMap