apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  platform: tanzu-ipp
bases:
  - ../base
resources:
  - resources/htdocs-configmap.yaml
patchesStrategicMerge:
  - patches/htdocs-configmap.yaml
