---
apiVersion: v1
kind: ConfigMap
metadata:
  name: htdocs-static
  namespace: tanzu-helm-resources
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head><title>It Works!</title></head>
      <body>
        <h1>Hello from the Base resource definition</h1>
      </body>
    </html>
  page2.txt: |
    This is another file on the htdocs configmap
    
